<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE sqlMap [
	<!ELEMENT sqlMap (typeAlias* | cacheModel* | resultMap* | parameterMap* | sql* | statement* | insert* | update* | delete* | select* | procedure*)+>
	<!ATTLIST sqlMap
	xmlns:fo CDATA #IMPLIED
	namespace CDATA #IMPLIED
	>
	
	<!ELEMENT parameterMap (parameter+)>
	<!ATTLIST parameterMap
	id CDATA #REQUIRED
	class CDATA #REQUIRED
	>
	<!ELEMENT parameter EMPTY>
	<!ATTLIST parameter
	property CDATA #REQUIRED
	javaType CDATA #IMPLIED
	jdbcType CDATA #IMPLIED
	typeName CDATA #IMPLIED
	nullValue CDATA #IMPLIED
	mode (IN | OUT | INOUT) #IMPLIED
	typeHandler CDATA #IMPLIED
	resultMap CDATA #IMPLIED
	numericScale CDATA #IMPLIED
	>
	<!ELEMENT resultMap (result*, discriminator?)>
	<!ATTLIST resultMap
	id CDATA #REQUIRED
	class CDATA #REQUIRED
	extends CDATA #IMPLIED
	xmlName CDATA #IMPLIED
	groupBy CDATA #IMPLIED
	>
	<!ELEMENT result EMPTY>
	<!ATTLIST result
	property CDATA #REQUIRED
	javaType CDATA #IMPLIED
	column CDATA #IMPLIED
	columnIndex CDATA #IMPLIED
	jdbcType CDATA #IMPLIED
	nullValue CDATA #IMPLIED
	select CDATA #IMPLIED
	resultMap CDATA #IMPLIED
	typeHandler CDATA #IMPLIED
	>
	<!ELEMENT discriminator (subMap+)>
	<!ATTLIST discriminator
	javaType CDATA #REQUIRED
	column CDATA #IMPLIED
	columnIndex CDATA #IMPLIED
	jdbcType CDATA #IMPLIED
	nullValue CDATA #IMPLIED
	typeHandler CDATA #IMPLIED
	>
	<!ELEMENT subMap EMPTY>
	<!ATTLIST subMap
	value CDATA #REQUIRED
	resultMap CDATA #REQUIRED
	>
	<!ELEMENT cacheModel (flushInterval?, flushOnExecute*, property*)+>
	<!ATTLIST cacheModel
	id CDATA #REQUIRED
	type CDATA #REQUIRED
	readOnly (true | false) #IMPLIED
	serialize (true | false) #IMPLIED
	>
	<!ELEMENT flushInterval EMPTY>
	<!ATTLIST flushInterval
	milliseconds CDATA #IMPLIED
	seconds CDATA #IMPLIED
	minutes CDATA #IMPLIED
	hours CDATA #IMPLIED
	>
	<!ELEMENT flushOnExecute EMPTY>
	<!ATTLIST flushOnExecute
	statement CDATA #REQUIRED
	>
	
	<!ELEMENT property EMPTY>
	<!ATTLIST property
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	>
	
	<!ELEMENT typeAlias EMPTY>
	<!ATTLIST typeAlias
	alias CDATA #REQUIRED
	type CDATA #REQUIRED
	>
	
	<!ELEMENT sql (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST sql
	id CDATA #REQUIRED
	>
	
	<!ELEMENT include EMPTY>
	<!ATTLIST include
	refid CDATA #REQUIRED
	>
	
	<!ELEMENT statement (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST statement
	id CDATA #REQUIRED
	parameterMap CDATA #IMPLIED
	parameterClass CDATA #IMPLIED
	resultMap CDATA #IMPLIED
	resultClass CDATA #IMPLIED
	cacheModel CDATA #IMPLIED
	resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
	fetchSize CDATA #IMPLIED
	xmlResultName CDATA #IMPLIED
	remapResults (true|false) #IMPLIED
	timeout CDATA #IMPLIED
	>
	
	<!ELEMENT select (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST select
	id CDATA #REQUIRED
	parameterMap CDATA #IMPLIED
	parameterClass CDATA #IMPLIED
	resultMap CDATA #IMPLIED
	resultClass CDATA #IMPLIED
	cacheModel CDATA #IMPLIED
	resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
	fetchSize CDATA #IMPLIED
	xmlResultName CDATA #IMPLIED
	remapResults (true|false) #IMPLIED
	timeout CDATA #IMPLIED
	>
	
	<!ELEMENT insert (#PCDATA | include | dynamic | selectKey | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST insert
	id CDATA #REQUIRED
	parameterMap CDATA #IMPLIED
	parameterClass CDATA #IMPLIED
	timeout CDATA #IMPLIED
	>
	
	<!ELEMENT selectKey (#PCDATA | include)*>
	<!ATTLIST selectKey
	resultClass CDATA #IMPLIED
	keyProperty CDATA #IMPLIED
	type (pre|post) #IMPLIED
	>
	
	<!ELEMENT update (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST update
	id CDATA #REQUIRED
	parameterMap CDATA #IMPLIED
	parameterClass CDATA #IMPLIED
	timeout CDATA #IMPLIED
	>
	
	<!ELEMENT delete (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST delete
	id CDATA #REQUIRED
	parameterMap CDATA #IMPLIED
	parameterClass CDATA #IMPLIED
	timeout CDATA #IMPLIED
	>
	
	<!ELEMENT procedure (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST procedure
	id CDATA #REQUIRED
	parameterMap CDATA #IMPLIED
	parameterClass CDATA #IMPLIED
	resultMap CDATA #IMPLIED
	resultClass CDATA #IMPLIED
	cacheModel CDATA #IMPLIED
	fetchSize CDATA #IMPLIED
	xmlResultName CDATA #IMPLIED
	remapResults (true|false) #IMPLIED
	timeout CDATA #IMPLIED
	>
	
	<!-- - - - - - - - - - - - - - - - - - - - - - - - -
	                 DYNAMIC ELEMENTS
	  - - - - - - - - - - - - - - - - - - - - - - - - -->
	
	<!ELEMENT dynamic (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST dynamic
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	>
	
	<!ELEMENT isNotNull (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isNotNull
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isNull (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isNull
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isNotPropertyAvailable (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isNotPropertyAvailable
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #REQUIRED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isPropertyAvailable (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isPropertyAvailable
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #REQUIRED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isEqual
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	compareProperty CDATA #IMPLIED
	compareValue CDATA #IMPLIED
	>
	
	<!ELEMENT isNotEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isNotEqual
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	compareProperty CDATA #IMPLIED
	compareValue CDATA #IMPLIED
	>
	
	<!ELEMENT isGreaterThan (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isGreaterThan
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	compareProperty CDATA #IMPLIED
	compareValue CDATA #IMPLIED
	>
	
	<!ELEMENT isGreaterEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isGreaterEqual
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	compareProperty CDATA #IMPLIED
	compareValue CDATA #IMPLIED
	>
	
	<!ELEMENT isLessThan (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isLessThan
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	compareProperty CDATA #IMPLIED
	compareValue CDATA #IMPLIED
	>
	
	<!ELEMENT isLessEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isLessEqual
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	compareProperty CDATA #IMPLIED
	compareValue CDATA #IMPLIED
	>
	
	<!ELEMENT isEmpty (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isEmpty
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isNotEmpty (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isNotEmpty
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isParameterPresent (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isParameterPresent
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT isNotParameterPresent (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST isNotParameterPresent
	prepend CDATA #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	removeFirstPrepend (true|false) #IMPLIED
	>
	
	<!ELEMENT iterate (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
	<!ATTLIST iterate
	prepend CDATA #IMPLIED
	property CDATA #IMPLIED
	removeFirstPrepend (true|false|iterate) #IMPLIED
	open CDATA #IMPLIED
	close CDATA #IMPLIED
	conjunction CDATA #IMPLIED
	>
]>

<sqlMap namespace="osgi.datasource.ds">
	<resultMap id="dataSourceVoResultMap" class="ttsoft.osgi.datasource.bean.DataSourceVo">
    	<result column="DSID" jdbcType="VARCHAR" property="dsId" />
    	<result column="DSMC" jdbcType="VARCHAR" property="dsMc" />
    	<result column="DSBM" jdbcType="VARCHAR" property="dsBm" />
    	<result column="DSLB" jdbcType="VARCHAR" property="dsLb" />
    	<result column="DSLX" jdbcType="VARCHAR" property="dsLx" />
    	<result column="DSDC" jdbcType="VARCHAR" property="dsDc" />
    	<result column="DSIP" jdbcType="VARCHAR" property="dsIp" />
    	<result column="DSPORT" jdbcType="NUMERIC" property="dsPort" />
    	<result column="DSNM" jdbcType="VARCHAR" property="dsNm" />
    	<result column="DSURL" jdbcType="VARCHAR" property="dsUrl" />
    	<result column="DSUSER" jdbcType="VARCHAR" property="dsUser" />
    	<result column="DSPASS" jdbcType="VARCHAR" property="dsPass" />
    	<result column="DSMIN" jdbcType="NUMRIC" property="dsMin" />
    	<result column="DSMAX" jdbcType="NUMRIC" property="dsMax" />
    	<result column="DSINIT" jdbcType="NUMRIC" property="dsInit" />
    	<result column="DSINC" jdbcType="NUMRIC" property="dsInc" />
    	<result column="XH" jdbcType="NUMRIC" property="xh" />
    	<result column="QYBZ" jdbcType="CHAR" property="qybz" />
  	</resultMap>
	<!-- 查询所有已启用的数据源定义数据 -->
	<select id="queryAllEnabled" resultMap="dataSourceVoResultMap">
		<![CDATA[
		select DSID, DSMC, DSBM, DSLX, DSLB, DSDC, DSIP, DSPORT, DSNM, DSURL, DSUSER, DSPASS, DSMIN, DSMAX, DSINIT, DSINC, XH, QYBZ 
		from TTSFT_DS
		where QYBZ is not null and (QYBZ = 'Y' or QYBZ = 'y' or QYBZ = '1')
        ]]>
	</select>
	<!-- 查询数据源定义数据数量 -->
	<select id="selectDsPageCount" parameterClass="java.util.Map" resultClass="int">
		<![CDATA[
		select count(DSID) from TTSFT_DS
		]]>
		<dynamic prepend="where">
			<isNotEmpty prepend="" property="vo">
				<isNotEmpty prepend=" and " property="vo.dsBm">
					<![CDATA[DSBM like '%$vo.dsBm$%']]>
				</isNotEmpty>
				<isNotEmpty prepend=" and " property="vo.dsMc">
					<![CDATA[DSMC like '%$vo.dsMc$%']]>
				</isNotEmpty>
				<isNotEmpty prepend=" and " property="vo.qybz">
					<![CDATA[QYBZ=#vo.qybz:VARCHAR#]]>
				</isNotEmpty>
			</isNotEmpty>
		</dynamic>
	</select>
	<!-- 分页查询数据源定义数据 -->
	<select id="selectDsPageData" parameterClass="java.util.Map" resultMap="dataSourceVoResultMap">
		<include refid="page.prefix" />
		<![CDATA[
		select * from TTSFT_DS
		]]>
		<dynamic prepend="where">
			<isNotEmpty prepend="" property="vo">
				<isNotEmpty prepend=" and " property="vo.dsBm">
					<![CDATA[DSBM like '%$vo.dsBm$%']]>
				</isNotEmpty>
				<isNotEmpty prepend=" and " property="vo.dsMc">
					<![CDATA[DSMC like '%$vo.dsMc$%']]>
				</isNotEmpty>
				<isNotEmpty prepend=" and " property="vo.qybz">
					<![CDATA[QYBZ=#vo.qybz:VARCHAR#]]>
				</isNotEmpty>
				
			</isNotEmpty>
		</dynamic>
		<include refid="page.suffix" />
		<![CDATA[
		order by XH
		]]>
	</select>
	<!-- 根据ID集合查询数据源定义数据 -->
	<select id="selectDSVoByIds" parameterClass="java.util.List" resultMap="dataSourceVoResultMap">
		<![CDATA[
		select * from TTSFT_DS where
		]]>
		<iterate open="(" close=")" conjunction=" or ">
            DSID = #[]:VARCHAR#
        </iterate>
	</select>
	<!-- 更新数据源标志数据
	Map['ids'] = List<String>
	Map['qybz'] = Y or N
	 -->
	<update id="updateQybz" parameterClass="java.util.Map">
		<![CDATA[
		update TTSFT_DS set QYBZ = #qybz:VARCHAR# where 
		]]>
		<iterate open="(" close=")" conjunction=" or " property="ids">
            DSID = #ids[]:VARCHAR#
        </iterate>
	</update>
	<delete id="deleteDSVoByIds" parameterClass="java.util.List">
		<![CDATA[
		delete from TTSFT_DS where 
		]]>
		<iterate open="(" close=")" conjunction=" or ">
            DSID = #[]:VARCHAR#
        </iterate>
	</delete>
	<insert id="insertDSVo" parameterClass="ttsoft.osgi.datasource.bean.DataSourceVo">
		<![CDATA[
		insert into TTSFT_DS (DSID, DSMC, DSBM, DSLX, DSLB, DSDC, DSIP, DSPORT, DSNM, DSURL, DSUSER, DSPASS, DSMIN, DSMAX, DSINIT, DSINC, XH, QYBZ)
		values(#dsId:VARCHAR#, #dsMc:VARCHAR#, #dsBm:VARCHAR#, #dsLx:VARCHAR#, #dsLb:VARCHAR#, #dsDc:VARCHAR#, 
		       #dsIp:VARCHAR#, #dsPort:NUMERIC#, #dsNm:VARCHAR#, 
		       #dsUrl:VARCHAR#, #dsUser:VARCHAR#, #dsPass:VARCHAR#, 
		       #dsMin:NUMRIC#, #dsMax:NUMRIC#, #dsInit:NUMRIC#, #dsInc:NUMRIC#, #xh:NUMRIC#, #qybz:CHAR#)
		]]>
	</insert>
	<select id="selectDsById" parameterClass="string" resultMap="dataSourceVoResultMap">
		<![CDATA[
		select DSID, DSMC, DSBM, DSLX, DSLB, DSDC, DSIP, DSPORT, DSNM, DSURL, DSUSER, DSPASS, DSMIN, DSMAX, DSINIT, DSINC, XH, QYBZ 
		from TTSFT_DS 
		where DSID = #value:VARCHAR#
        ]]>
	</select>
	<update id="updateDSVo" parameterClass="ttsoft.osgi.datasource.bean.DataSourceVo">
		<![CDATA[
		update TTSFT_DS  
		]]>
		<dynamic prepend="set">
			<isNotEmpty prepend="," property="dsMc">
                <![CDATA[DSMC=#dsMc:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsBm">
                <![CDATA[DSBM=#dsBm:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsLx">
                <![CDATA[DSLX=#dsLx:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsLb">
                <![CDATA[DSLB=#dsLb:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsDc">
                <![CDATA[DSDC=#dsDc:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsIp">
                <![CDATA[DSIP=#dsIp:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsPort">
                <![CDATA[DSPORT=#dsPort:NUMERIC#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsNm">
                <![CDATA[DSNM=#dsNm:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsUrl">
                <![CDATA[DSURL=#dsUrl:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsUser">
                <![CDATA[DSUSER=#dsUser:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsPass">
                <![CDATA[DSPASS=#dsPass:VARCHAR#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsMin">
                <![CDATA[DSMIN=#dsMin:NUMRIC#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsMax">
                <![CDATA[DSMAX=#dsMax:NUMRIC#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsInit">
                <![CDATA[DSINIT=#dsInit:NUMRIC#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="dsInc">
                <![CDATA[DSINC=#dsInc:NUMRIC#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="xh">
                <![CDATA[XH=#xh:NUMRIC#]]>
            </isNotEmpty>
            <isNotEmpty prepend="," property="qybz">
                <![CDATA[QYBZ=#qybz:VARCHAR#]]>
            </isNotEmpty>
		</dynamic>
		<![CDATA[
		where DSID = #dsId:VARCHAR#
        ]]>
	</update>
</sqlMap>